// Package deploy handles GitHub repo creation and Vercel deployment for
// ventures in the Kivo pipeline. It uses raw HTTP calls to the GitHub and
// Vercel APIs to keep external dependencies minimal.
package deploy

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

const (
	defaultGitHubBaseURL = "https://api.github.com"
	defaultVercelBaseURL = "https://api.vercel.com"
)

// Deployer manages GitHub repo creation and Vercel deployment.
type Deployer struct {
	githubToken string
	vercelToken string
	githubOrg   string

	// Exposed for testing -- override to point at httptest servers.
	GitHubBaseURL string
	VercelBaseURL string

	httpClient *http.Client
}

// New creates a Deployer with the given credentials.
func New(githubToken, vercelToken, githubOrg string) *Deployer {
	return &Deployer{
		githubToken:   githubToken,
		vercelToken:   vercelToken,
		githubOrg:     githubOrg,
		GitHubBaseURL: defaultGitHubBaseURL,
		VercelBaseURL: defaultVercelBaseURL,
		httpClient:    http.DefaultClient,
	}
}

// ---------- GitHub: Create Repository ----------

// createRepoRequest is the payload for POST /orgs/{org}/repos.
type createRepoRequest struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Private     bool   `json:"private"`
	AutoInit    bool   `json:"auto_init"`
}

// createRepoResponse captures the fields we need from GitHub's response.
type createRepoResponse struct {
	HTMLURL string `json:"html_url"`
	FullName string `json:"full_name"`
}

// CreateRepo creates a new public GitHub repository under the configured org.
// It returns the repo's HTML URL (e.g. https://github.com/Kivo-Agentic-Ventures/my-venture).
func (d *Deployer) CreateRepo(ctx context.Context, name string) (string, error) {
	payload := createRepoRequest{
		Name:        name,
		Description: fmt.Sprintf("Landing page for %s — generated by Kivo", name),
		Private:     false,
		AutoInit:    false,
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("marshaling create repo request: %w", err)
	}

	url := fmt.Sprintf("%s/orgs/%s/repos", d.GitHubBaseURL, d.githubOrg)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("creating request: %w", err)
	}

	d.setGitHubHeaders(req)

	resp, err := d.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("calling github create repo: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("reading github response: %w", err)
	}

	if resp.StatusCode != http.StatusCreated {
		return "", fmt.Errorf("github create repo returned %d: %s", resp.StatusCode, string(respBody))
	}

	var result createRepoResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("parsing github response: %w", err)
	}

	return result.HTMLURL, nil
}

// ---------- GitHub: Push Files ----------

// putContentsRequest is the payload for PUT /repos/{owner}/{repo}/contents/{path}.
type putContentsRequest struct {
	Message string `json:"message"`
	Content string `json:"content"` // base64-encoded file content
	Branch  string `json:"branch,omitempty"`
}

// PushFiles creates or updates files in the given GitHub repo. The files map
// keys are paths (e.g. "index.html") and values are the raw file content.
// Each file is committed individually via the Contents API.
func (d *Deployer) PushFiles(ctx context.Context, repoName string, files map[string]string) error {
	for path, content := range files {
		if err := d.pushFile(ctx, repoName, path, content); err != nil {
			return fmt.Errorf("pushing %s: %w", path, err)
		}
	}
	return nil
}

// pushFile creates or updates a single file via the GitHub Contents API.
func (d *Deployer) pushFile(ctx context.Context, repoName, filePath, content string) error {
	payload := putContentsRequest{
		Message: fmt.Sprintf("Add %s", filePath),
		Content: base64.StdEncoding.EncodeToString([]byte(content)),
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshaling put contents request: %w", err)
	}

	url := fmt.Sprintf("%s/repos/%s/%s/contents/%s", d.GitHubBaseURL, d.githubOrg, repoName, filePath)
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, url, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("creating request: %w", err)
	}

	d.setGitHubHeaders(req)

	resp, err := d.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("calling github put contents: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("reading github response: %w", err)
	}

	// GitHub returns 201 for create, 200 for update.
	if resp.StatusCode != http.StatusCreated && resp.StatusCode != http.StatusOK {
		return fmt.Errorf("github put contents returned %d: %s", resp.StatusCode, string(respBody))
	}

	return nil
}

// ---------- Vercel: Deploy ----------

// vercelDeployRequest is the payload for POST /v13/deployments.
type vercelDeployRequest struct {
	Name   string                `json:"name"`
	GitSource *vercelGitSource   `json:"gitSource,omitempty"`
	ProjectSettings *vercelProjectSettings `json:"projectSettings,omitempty"`
}

type vercelGitSource struct {
	Type string `json:"type"`
	Org  string `json:"org"`
	Repo string `json:"repo"`
	Ref  string `json:"ref"`
}

type vercelProjectSettings struct {
	Framework       *string `json:"framework"`
	OutputDirectory string  `json:"outputDirectory,omitempty"`
}

// vercelDeployResponse captures the fields we need from Vercel's response.
type vercelDeployResponse struct {
	ID  string `json:"id"`
	URL string `json:"url"`
}

// DeployToVercel triggers a Vercel deployment from the GitHub repo. It uses the
// Vercel deployment API with a git source pointing at the org/repo. Returns the
// live site URL (https://<url>) and the deployment ID.
func (d *Deployer) DeployToVercel(ctx context.Context, repoName string) (siteURL string, err error) {
	// Static site -- no framework, output from root.
	noFramework := ""
	payload := vercelDeployRequest{
		Name: repoName,
		GitSource: &vercelGitSource{
			Type: "github",
			Org:  d.githubOrg,
			Repo: repoName,
			Ref:  "main",
		},
		ProjectSettings: &vercelProjectSettings{
			Framework: &noFramework,
		},
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("marshaling vercel deploy request: %w", err)
	}

	url := fmt.Sprintf("%s/v13/deployments", d.VercelBaseURL)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("creating request: %w", err)
	}

	d.setVercelHeaders(req)

	resp, err := d.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("calling vercel deploy: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("reading vercel response: %w", err)
	}

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		return "", fmt.Errorf("vercel deploy returned %d: %s", resp.StatusCode, string(respBody))
	}

	var result vercelDeployResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("parsing vercel response: %w", err)
	}

	if result.URL == "" {
		return "", fmt.Errorf("vercel returned empty URL")
	}

	return fmt.Sprintf("https://%s", result.URL), nil
}

// ---------- Helpers ----------

func (d *Deployer) setGitHubHeaders(req *http.Request) {
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Authorization", "Bearer "+d.githubToken)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")
}

func (d *Deployer) setVercelHeaders(req *http.Request) {
	req.Header.Set("Authorization", "Bearer "+d.vercelToken)
	req.Header.Set("Content-Type", "application/json")
}
